#!/bin/bash

if ! test -z "$1"
then
    session=$1
    echo $session > ~/.session_id
elif test -e ~/.session_id
then
    session=$(cat ~/.session_id)
fi

if test -z "$session"
then
    echo "USAGE: $0 [Session ID]"
    echo
    echo "If you do not provide a session id, it must exist in .session_id"

    exit 1
fi

MODULE="ELEC6200"
YEAR=$(date +%y)
YEAR=$(expr $YEAR - 1)$YEAR
NOTES=https://secure.ecs.soton.ac.uk/notes/$(echo $MODULE | tr '[:upper:]' '[:lower:]')
E_MARKING=/e_marking/feedback/$MODULE/$YEAR/Final/marks1.php
URL=$NOTES$E_MARKING

cd /tmp

wget --quiet --header="Cookie: ecs_intra_session=$session" $URL

if test -e last.txt && (! diff -q last.txt marks1.php > /dev/null)
then
    echo " GDP Change Detected!"
    echo ""
    echo "#FF0000"

    rm marks1.php
else
    mv -f marks1.php last.txt

    echo ""
    echo ""
    echo "#FFFFFF"
fi

exit 0
